SELECT
    FNAME,
    LNAME
FROM
    MENDO_STUDENT
WHERE
    SSN IN (
        SELECT
            SSN
        FROM
            MENDO_STUDENT_CLASS
        WHERE
            CLASS_CODE =(
                SELECT
                    CLASS_CODE
                FROM
                    MENDO_CLASS
                WHERE
                    LOWER(CLASS_DESCRIPTION) = 'database programming'
            )
    );

SELECT * FROM STUDENT_CLASS WHERE CLASS_CODE IN (SELECT CLASS_CODE FROM CLASS WHERE CLASS_DESCRIPTION IS NOT NULL);

SELECT FNAME, LNAME FROM STUDENT WHERE SSN IN 
(SELECT SSN FROM STUDENT_CLASS WHERE CLASS_CODE = (SELECT CLASS_CODE FROM CLASS WHERE UPPER(CLASS_DESCRIPTION) = 'OPERATING SYSTEMS'))
AND (UPPER(FNAME) NOT IN ('JOHN', 'JACK', 'BOB') AND PHONE IS NOT NULL);