SELECT COUNT(FNAME) AS NUMOFPEOPLE, PARTYID AS PARTY FROM CANDIDATE GROUP BY PARTYID ORDER BY PARTID;

SELECT COUNT(FNAME) AS NUMOFPEOPLE, PARTYID AS PARTY FROM CANDIDATE WHERE FNAME LIKE 'd%' OR FNAME like '%r' GROUP BY PARTYID;

SELECT PARTYID AS PARTY, AVG(SALARY) FROM CANDIDATE GROUP BY PARTYID;

SELECT PARTYID AS PARTY, COUNT(FNAME) AS NUMOFPEOPLE FROM CANDIDATE GROUP BY PARTID HAVING COUNT (FNAME) <= 2;